ALTER TABLE public.jurisdiction
	ADD COLUMN is_validated_timezone BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_importantdates BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_phones BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_urls BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_notices BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_locations BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_published BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.wip_jurisdiction
	ADD COLUMN is_validated_timezone BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_importantdates BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_phones BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_urls BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_notices BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_locations BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_published BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.location
	ADD COLUMN is_validated_name BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_wayfinding BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_timezone BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_phones BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_email BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_hours BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_rules BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_useflags BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_displaynotes BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN display_note TEXT;

ALTER TABLE public.wip_location
	ADD COLUMN is_validated_name BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_wayfinding BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_timezone BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_phones BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_email BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_hours BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_rules BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_useflags BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN is_validated_displaynotes BOOLEAN NOT NULL DEFAULT FALSE ,
	ADD COLUMN display_note TEXT;

